number_list =[1,2,3,1,10,15]
number_list.append(20)
print(number_list)
number_list.insert(1,7)
print(number_list)
number_list.remove(2)
print(number_list)
print(1 in number_list)
number_list.pop()
print(number_list)
print(number_list.count(1))
print(number_list.index(10))
number_list_2 = number_list.copy()
number_list.clear()
print(number_list_2)
